### ISSUE TITLE
Issue with Installation Test

### ISSUE THREAD

**Issue by alishbaimran** [KosinskiLab/pyTME#6] opened 2024-04-13 23:40 UTC
Hey! I followed the conda installation requirements on the website (https://kosinskilab.github.io/pyTME/quickstart/installation.html#installation-section) but get the following errors when running pytest:
<img width="1141" alt="Screenshot 2024-04-13 at 4 40 01 PM" src="https://github.com/KosinskiLab/pyTME/assets/44557946/2309ca8c-a57f-49ba-adde-c06cc99d9c5b">

Could anyone help with resolving these?

**Comment by maurerv** [comment] 2024-04-14 12:26
Hi @alishbaimran,

Which version of pyTME are you using? :)

The first five errors are related to pyTME being unable to read tiff files. This is because pyTME relies on an external dependency, which we recently changed to obligatory instead of optional. You can fix these issues by installing the dependency from within the conda environment that contains pyTME: `pip install tifffile`

The last failed test case seems to be related to numerical precision.  On which operating system did you run the tests?

However, overall the installation looks fine and you should be ready to apply pyTME to your use case :)

**Comment by alishbaimran** [comment] 2024-04-14 18:32
Got it! I did the pip command (and conda install tifffile -c conda-forge) but was not able to resolve the tiff file errors. I'm also still having the numerical precision error. I'm on Ubuntu 22.04 LTS. 
<img width="1082" alt="Screenshot 2024-04-14 at 11 32 31 AM" src="https://github.com/KosinskiLab/pyTME/assets/44557946/030ba0a8-21f8-48c2-ad3e-1e65eea0802f">

**Comment by alishbaimran** [comment] 2024-04-14 18:36
<img width="1024" alt="Screenshot 2024-04-14 at 11 32 58 AM" src="https://github.com/KosinskiLab/pyTME/assets/44557946/9df88b8d-2a5e-4e25-97ab-8178bebb9584">

**Comment by maurerv** [comment] 2024-04-14 19:49
Could you kindly run `pytest > log.txt`  and upload the created log.txt here? That would help a lot with troubleshooting.

**Comment by alishbaimran** [comment] 2024-04-14 20:56
Attached!
[log.txt](https://github.com/KosinskiLab/pyTME/files/14972105/log.txt)

**Comment by maurerv** [comment] 2024-04-15 11:41
Thanks for providing the log!

I was able to reproduce your issues with the pyTME docker setup. The observed behavior was unintended and addressed in the recent commit 68ffb21fb87b9cde1e19852528e85c791519c9e8.

You can apply the changes by reinstalling from within your conda environment `python3.11 -mpip install -U --force-reinstall git+https://github.com/KosinskiLab/pyTME`. Please also clone the newest version of the repository before running the test cases :)

**Closed as completed** 2024-04-20 21:30 UTC
